# Generated by Django 4.1.3 on 2022-11-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_list', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default='text'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
