# Generated by Django 4.1.3 on 2022-11-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_list', '0004_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
