# Generated by Django 4.1.3 on 2022-11-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_list', '0006_expense_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='create',
            new_name='date',
        ),
    ]
