# Generated by Django 4.1.3 on 2022-11-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_list', '0007_alter_expense_options_rename_create_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
