# Generated by Django 4.1.3 on 2022-12-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_list', '0010_alter_expense_date_friendslist_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='account',
        ),
        migrations.RemoveField(
            model_name='friendslist',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
